# Generated by Django 5.2.5 on 2026-09-05 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0002_maquinas_numeroserie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('idEstado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('idJuego', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('idProveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('idResultado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreResultado', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TiposAplicativos',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('idTipoAplicativo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreTipoAplicativo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TiposPruebas',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('idTipoPrueba', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreTipoPrueba', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('idPrueba', models.BigAutoField(primary_key=True, serialize=False)),
                ('idDetallePrueba', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fechaPuestaPunto', models.DateField(blank=True, null=True)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('idEncargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_encargadas', to=settings.AUTH_USER_MODEL)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='pruebas.estados')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='pruebas.resultados')),
                ('idTipoPrueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='pruebas.tipospruebas')),
            ],
        ),
        migrations.CreateModel(
            name='PruebasMaquinas',
            fields=[
                ('idPruebaMaquina', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigoPrueba', models.CharField(max_length=100, unique=True)),
                ('idJuego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_maquinas', to='pruebas.juegos')),
                ('idMaquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_maquinas', to='maquinas.maquinas')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_maquinas', to='pruebas.proveedores')),
                ('idPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_maquinas', to='pruebas.pruebas')),
            ],
        ),
        migrations.CreateModel(
            name='PruebasAplicativos',
            fields=[
                ('idPruebaAplicativo', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigoPrueba', models.CharField(max_length=100, unique=True)),
                ('idDesarrollador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_desarrolladas', to=settings.AUTH_USER_MODEL)),
                ('idPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_aplicativos', to='pruebas.pruebas')),
                ('idTipoAplicativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_aplicativos', to='pruebas.tiposaplicativos')),
            ],
        ),
    ]
