# Generated by Django 5.2.5 on 2026-08-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionesLaboratorio',
            fields=[
                ('idPosicion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePosicion', models.CharField(max_length=25)),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('idMaquina', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreMaquina', models.CharField(max_length=25)),
                ('juego', models.CharField(max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('idPosicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.posicioneslaboratorio')),
            ],
        ),
    ]
