# Generated by Django 5.2.5 on 2026-09-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas',
            name='numeroSerie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
